---
- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
  listen: restart telegraf

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  listen: apt update
